; Main backpop settings
[backpop]

n_threads = 2
n_eff = 8000
n_live = 1000
verbose = true
output_folder = ../../example_inis/simple_METISSE_output
resume = false

phase_condition = kstar_1 == 1 & kstar_2 == 1
MRR = true

bpp_columns =
n_bpp_rows = 

use_bcm = False
bcm_columns =

; Observational constraints
[backpop.obs::m1]
mean = 35
sigma = 1
out_name = mass_1

[backpop.obs::m2]
mean = 5
sigma = 0.05
out_name = mass_2

[backpop.obs::tb]
mean = 2500.0
sigma = 50.0
out_name = porb

[backpop.obs::e]
mean = 0.3
sigma = 0.02
out_name = ecc

[backpop.fixed::metallicity]
value = 0.001

[backpop.fixed::tphys]
value = 10.0

; Prior info on parameters to vary
[backpop.var::m1]
min = 5.0
max = 50.0

[backpop.var::m2]
min = 2
max = 8

[backpop.var::tb]
min = 5.0
max = 5000.0

[backpop.var::e]
min = 0.0
max = 0.9

; Random seed for COSMIC
[rand_seed]
seed = 42

; Single star evolution settings 
[sse]
stellar_engine = metisse
path_to_tracks = /path/to/hydrogen/tracks
path_to_he_tracks = /path/to/helium/tracks
z_accuracy_limit = 0.01
metisse_verbose = False